### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by mainguyenanhvu** [CSBG-LSU/BionoiNet#4]
After I installed biopandas by `pip install biopandas`, I faced with the error when running img_gen.sh:
```
colorby:
residue_type
input directory:
../../homology_reduced_mols/control/fold_1
output directory:
../../bionoi_output/residue_type/homology_reduced_mols/control/
pop directory:
../../pop_folder/homology_reduced_mols/
profile directory:
../../profile_folder/homology_reduced_mols/

1a5iA00-1.mol2
Matplotlib is building the font cache using fc-list. This may take a moment.
Fontconfig warning: ignoring UTF-8: not a valid region tag
Traceback (most recent call last):
  File "bionoi.py", line 16, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
1b25C00-1.mol2
Traceback (most recent call last):
  File "bionoi.py", line 16, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

I tried to install opencv by using conda (`conda install opencv`) but it is conflicted:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - cycler==0.10.0=py36_0 -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.5,<3.6.0a0']
  - h5py==2.9.0 -> python[version='<3|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.5,<3.6.0a0']
  - imageio==2.5.0=py36_0 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - mkl_fft==1.0.12=py36ha843d7b_0 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - mkl_random==1.0.2=py36hd81dba3_0 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - numpy==1.16.3=py36h7e9f1db_0 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - pandas==0.24.2=py36he6710b0_0 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - pillow==6.0.0=py36h34e0f95_0 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0']
  - pip==19.1.1=py36_0 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.11,<3.12.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - pyqt==5.9.2=py36h05f1152_2 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
  - python-dateutil==2.8.0=py36_0 -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.5,<3.6.0a0']
  - pytorch==1.0.1=cuda92py36h65efead_0 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.5,<3.6.0a0']
  - pywavelets==1.0.3=py36hdd07704_1 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - scipy==1.2.1=py36h7c811a0_0 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - setuptools==41.0.1=py36_0 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - torchvision==0.2.1=py36_0 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - wheel==0.33.4=py36_0 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.11,<3.12.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python==3.6.8=h0371630_0

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
``` 

Please show me the version of opencv and how it was installed so that I can install it. Thank you very much.

p/s: I found 3 ways:
1. Use conda: conda install -c conda-forge opencv
2. pip install opencv-python
3. from source: https://docs.opencv.org/4.x/d7/d9f/tutorial_linux_install.html

**Comment by mainguyenanhvu** [comment]
I used option 2 to complete it.
